colorscheme molokai
syntax enable
set tabstop=4
set softtabstop=4
set expandtab
set number
set showcmd
set cursorline
set wildmenu
set foldenable
set foldlevelstart=10
set foldnestmax=10
set listchars=space:·
set list
set colorcolumn=72
